/* eslint-disable @next/next/no-sync-scripts */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google"
import Navbar from "@/components/Navbar/page";
import Sidebar from "@/components/Sidebar/page";
import { AppContextProvider } from "@/context/AppContext";
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config'
import { Web3ModalProvider } from '@/context'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { headers } from "next/headers";
import { SocketProvider } from "./providers";

// import WalletContextProvider from '@/context/WalletContextProvider'

export const metadata: Metadata = {
  title: "Dexup",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/icon.png' },
      new URL('/icon.png', 'https://dexup.io'),
      { url: '/icon-dark.png', media: '(prefers-color-scheme: dark)' },
    ],
    shortcut: ['/shortcut-icon.png'],
    apple: [
      { url: '/apple-icon.png' },
      { url: '/apple-icon-x3.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      {
        rel: 'apple-touch-icon-precomposed',
        url: '/apple-touch-icon-precomposed.png',
      },
    ],
  },
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {

  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <>
    
    <SocketProvider>
    <html lang="en" suppressHydrationWarning>
      <head>
      <script src="https://terminal.jup.ag/main-v1.js" data-preload />
      </head>
      <body className={`${fontSans.variable} bgradient w-screen h-screen text-white font-sans antialiased overflow-x-hidden`}>
      {/* <WalletContextProvider> */}

      <ToastContainer
        position="top-center"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
        />
          <Web3ModalProvider initialState={initialState}>

        <AppContextProvider>
        <div className="flex">
          <Sidebar/>
          <Navbar/>
            <main className="flex justify-center items-center w-full container mx-auto my-28">
            {children}
            </main>
        </div>
          </AppContextProvider>

          </Web3ModalProvider>

        {/* </WalletContextProvider> */}

      </body>
    </html>
    
    </SocketProvider>
    
    </>
  );
}
